baseURL = 'https://chaoneil.github.io/'
languageCode = 'en-us'
title = "ChaoNEil"
theme='hello-friend-ng'

paginate = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "I'm an aspiring security analyst. Website in progress"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"


    [languages.en.params.logo]
      logoText = "hello friend.."
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  [[menu.main]]
    identifier = "whoami"
    name       = "Whoami"
    url        = "whoami/"


# Addon: Social icons

[[params.social]]
    name = "linkedin"
    url = "www.linkedin.com/in/chao-neil-aryan-borgohain-264724175"
    
[[params.social]]
    name = "hackthebox"
    url = "https://app.hackthebox.com/profile/1277083"

[[params.social]]
    name = "tryhackme"
    url = "https://tryhackme.com/p/ChaoNEil"

[[params.social]]
    name = "twitter"
    url  = "https://twitter.com/NBorgan"

